export interface Star {
    x: number;
    y: number;
    size?: number;
    name?: string;
    owner?: string;
    sector?: string;
    isDestroyed?: boolean;
}
export const stars: Star[] = [{
    x: 864,
    y: 472,
    size: 3,
    name: "Эллис",
    owner: "Federation", sector: "Federation",
},
{
    x: 931,
    y: 569,
    size: 3,
    name: "Абрегадо-Рей",
    owner: "Federation", sector: "Federation",
},
{
    x: 990,
    y: 463,
    size: 3,
    name: "Скирнис",
    owner: "Federation", sector: "Federation",
},
{
    x: 1184,
    y: 618,
    size: 3,
    name: "Саврус",
    owner: "Federation", sector: "Federation3",
},
{
    x: 1013,
    y: 334,
    size: 7,
    name: "Нор-Гейд",
    owner: "Federation", sector: "Federation",
},
{
    x: 1122,
    y: 434,
    size: 3,
    name: "Эллис II",
    owner: "Federation", sector: "Federation",
},
{
    x: 1233,
    y: 473,
    size: 3,
    name: "Рамаленр",
    owner: "Federation", sector: "Federation3",
},
{
    x: 1320,
    y: 544,
    size: 3,
    name: "Галлен",
    owner: "Federation", sector: "Federation3",
},
{
    x: 1326,
    y: 382,
    size: 3,
    name: "Ярин",
    owner: "Federation", sector: "Federation3",
},
{
    x: 1419,
    y: 428,
    size: 3,
    name: "Лидирум",
    owner: "Federation", sector: "Federation3",
},
{
    x: 1303,
    y: 487,
    size: 3,
    name: "Альфарий",
    owner: "Federation", sector: "Federation3",
},
{
    x: 1427,
    y: 537,
    size: 3,
    name: "Криол-Тау",
    owner: "Federation", sector: "Federation3",
},
{
    x: 1488,
    y: 471,
    size: 3,
    name: "Эстдайн",
    owner: "Federation", sector: "Federation3",
},
{
    x: 256,
    size: 3,
    y: 1353,
    name: "Мельхраг",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 297,
    y: 1282,
    size: 3,
    name: "Ауракс",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 401,
    y: 1262,
    size: 3,
    name: "Опсида",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 434,
    size: 3,
    y: 1200,
    name: "Опсида-2",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 538,
    size: 3,
    y: 1190,
    name: "Врата Омегона",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 591,
    size: 3,
    y: 1255,
    name: "Омегон",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 655,
    size: 3,
    y: 1310,
    name: "Омегон II",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 715,
    size: 3,
    y: 1262,
    name: "Омегон III",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 520,
    size: 3,
    y: 1107,
    name: "Альфа-Центавра",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 299,
    size: 3,
    y: 1141,
    name: "Опсида 3",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 325,
    size: 3,
    y: 1044,
    name: "Малендар",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 389,
    size: 3,
    y: 1030,
    name: "Сириус",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 556,
    size: 3,
    y: 1036,
    name: "Хелган",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 634,
    size: 3,
    y: 1066,
    name: "Сирий",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 723,
    size: 3,
    y: 1047,
    name: "Новатерра",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 676,
    size: 3,
    y: 992,
    name: "Даэдалус",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 443,
    size: 3,
    y: 957,
    name: "Солнце",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 498,
    size: 3,
    y: 853,
    name: "Альтаир",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 427,
    size: 3,
    y: 811,
    name: "Венона",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 323,
    size: 3,
    y: 792,
    name: "Кентавр",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 191,
    y: 833,
    size: 3,
    name: "Ренин",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 368,
    y: 693,
    size: 3,
    name: "Мальрок",
    owner: "Alliance", sector: "Alliance"
},
{
    x: 198,
    size: 3,
    y: 747,
    name: "Бисмарк",
    owner: "Alliance", sector: "Alliance"
},
{
    name: "LV-223",
    x: 1890,
    y: 990,
    size: 3,
},
{
    x: 1046,
    size: 3,
    y: 726,
    name: "Кассиния",
    owner: "Empire", sector: "Empire",
},
{
    x: 1123,
    y: 780,
    size: 3,
    name: "Нираган",
    owner: "Empire", sector: "Empire",
},
{
    x: 1002,
    y: 794,
    size: 3,
    name: "Варул",
    owner: "Empire", sector: "Empire",
},
{
    x: 1166,
    y: 808,
    size: 3,
    name: "Ферриска",
    owner: "Empire", sector: "Empire",
},
{
    x: 1021,
    y: 859,
    size: 3,
    name: "Меран",
    owner: "Empire", sector: "Empire",
},
{
    x: 1148,
    y: 863,
    size: 3,
    name: "Омекрон",
    owner: "Empire", sector: "Empire",
},
{
    x: 1095,
    y: 890,
    size: 3,
    name: "Палте-Хагадан",
    owner: "Empire", sector: "Empire",
},
{
    x: 942,
    y: 911,
    size: 3,
    name: "Псалион",
    owner: "Empire", sector: "Empire",
},
{
    x: 1238,
    y: 942,
    size: 3,
    name: "Гулиар",
    owner: "Empire", sector: "Empire",
},
{
    x: 926,
    y: 969,
    size: 3,
    name: "Псилион",
    owner: "Empire", sector: "Empire",
},
{
    x: 1137,
    y: 1022,
    size: 3,
    name: "Хагадан",
    owner: "Empire", sector: "Empire",
},
{
    x: 1236,
    y: 1087,
    size: 3,
    name: "Рени",
    owner: "Empire", sector: "Empire",
},
{
    x: 958,
    y: 1173,
    size: 3,
    name: "Дальний",
    owner: "Empire", sector: "Empire",
},
{
    x: 1210,
    y: 1153,
    size: 3,
    name: "Элизиум",
    owner: "Empire", sector: "Empire",
},
{
    x: 1295,
    y: 1178,
    size: 3,
    name: "Лзорон",
    owner: "Empire", sector: "Empire",
},
{
    x: 1170,
    y: 1196,
    size: 3,
    name: "Жакрегор",
    owner: "Empire", sector: "Empire",
},
{
    x: 1150,
    y: 1268,
    size: 3,
    name: "Сринирус",
    owner: "Empire", sector: "Empire",
},
{
    x: 1214,
    y: 1311,
    size: 3,
    name: "Чира",
    owner: "Empire", sector: "Empire",
},
{
    x: 1032,
    y: 1373,
    size: 3,
    name: "Шрекон",
    owner: "Empire", sector: "Empire",
},
{
    x: 1448,
    y: 753,
    name: "Мирезон",
    owner: "Dominion", sector: "Dominion",
    size: 3,
},
{
    x: 1416,
    y: 852,
    name: "Палте-Минертар",
    owner: "Dominion", sector: "Dominion",
    size: 2,
},
{
    x: 1437,
    y: 1052,
    name: "Криос",
    owner: "Dominion", sector: "Dominion",
    size: 3,
},
{
    x: 1681,
    y: 1090,
    name: "Деваст",
    owner: "Dominion", sector: "Dominion",
    size: 5,
},
{
    x: 1565,
    y: 897,
    name: "Минертар",
    owner: "Dominion", sector: "Dominion",
    size: 6,
},
{
    x: 1650,
    y: 531,
    name: "Скиммар",
    owner: "Federation", sector: "Federation2",
    size: 3,
},
{
    x: 1724,
    y: 624,
    name: "Кшаоль",
    owner: "Federation", sector: "Federation2",
    size: 3,
},
{
    x: 1763,
    y: 561,
    name: "Мун-Матари",
    owner: "Federation", sector: "Federation2",
    size: 5,
},
{
    x: 1836,
    y: 533,
    name: "Мрсиррмс",
    owner: "Federation", sector: "Federation2",
    size: 1,
},
{
    x: 1877,
    y: 603,
    name: "Ангеоль",
    owner: "Federation", sector: "Federation2",
    size: 3,
},
{
    x: 1973,
    y: 614,
    name: "Краде-Римма",
    owner: "Federation", sector: "Federation2",
    size: 4,
},
{
    x: 1837,
    y: 677,
    name: "Фарлдар",
    owner: "Federation", sector: "Federation2",
    size: 6,
},
{
    x: 1841,
    y: 767,
    name: "Шсркиль",
    owner: "Federation", sector: "Federation2",
    size: 4,
},
{
    x: 1964,
    y: 855,
    name: "Мрсагеол",
    owner: "Federation", sector: "Federation2",
    size: 6,
},
{
    x: 1943,
    y: 988,
    name: "Фргиольн",
    owner: "Federation", sector: "Federation2",
    size: 1,
},
{
    x: 2127,
    y: 96,
    name: "Шира",
    owner: "Jericho", sector: "RedSector",
    size: 5,
},
{
    x: 2022,
    y: 142,
    name: "Свере Краэ",
    owner: "Jericho", sector: "RedSector",
    size: 4,
},
{
    x: 1925,
    y: 253,
    name: "Ладеш",
    owner: "Jericho", sector: "RedSector",
    size: 5,
},
{
    x: 2006,
    y: 268,
    name: "Слимирзг",
    owner: "Jericho", sector: "RedSector",
    size: 6,
},
{
    x: 2174,
    y: 278,
    name: "Редд",
    owner: "Jericho", sector: "RedSector",
    size: 6,
},
{
    x: 2335,
    y: 306,
    name: "Мегион",
    owner: "Jericho", sector: "RedSector",
    size: 1,
},
{
    x: 1943,
    y: 345,
    name: "Шлио",
    owner: "Jericho", sector: "RedSector",
    size: 2,
},
{
    x: 2056,
    y: 369,
    name: "Рассрейн",
    owner: "Jericho", sector: "RedSector",
    size: 3,
},
{
    x: 2163,
    y: 429,
    name: "Дорн",
    owner: "Jericho", sector: "RedSector",
    size: 1,
},
{
    x: 2258,
    y: 400,
    name: "Таурмель",
    owner: "Jericho", sector: "RedSector",
    size: 5,
},
{
    x: 2002,
    y: 468,
    name: "Варден",
    owner: "Jericho", sector: "RedSector",
    size: 6,
},
{
    x: 2139,
    y: 514,
    name: "Фари",
    owner: "Jericho", sector: "RedSector",
    size: 3,
},
{
    x: 2073,
    y: 535,
    name: "Южени Краэ",
    owner: "Jericho", sector: "RedSector",
    size: 3,
},
{
    x: 2209,
    y: 607,
    name: "Красне Краэ",
    owner: "Jericho", sector: "RedSector",
    size: 5,
},
{
    x: 2314,
    y: 485,
    name: "Жиренег",
    owner: "Jericho", sector: "RedSector",
    size: 4,
},
{
    x: 1138,
    y: 1669,
    name: "Леннир",
    owner: "Empire", sector: "Empire2",
    size: 4,
},
{
    x: 1287,
    y: 1591,
    name: "Эпсилон-4",
    owner: "Empire", sector: "Empire2",
    size: 5,
},
{
    x: 1331,
    y: 1706,
    name: "Хагадир",
    owner: "Empire", sector: "Empire2",
    size: 3,
},
{
    x: 1400,
    y: 1555,
    name: "Кратор",
    owner: "Empire", sector: "Empire2",
    size: 4,
},
{
    x: 1449,
    y: 1612,
    name: "Гаммариэль",
    owner: "Empire", sector: "Empire2",
    size: 1,
},
{
    x: 1445,
    y: 1701,
    name: "Вэриан",
    owner: "Empire", sector: "Empire2",
    size: 1,
},
{
    x: 1560,
    y: 1617,
    name: "Влеунск",
    owner: "Empire", sector: "Empire2",
    size: 1,
},
{
    x: 1592,
    y: 1718,
    name: "Приград",
    owner: "Empire", sector: "Empire2",
    size: 3,
},
{
    x: 1341,
    y: 1396,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 3,
},
{
    x: 1548,
    y: 1267,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 7,
},
{
    x: 1707,
    y: 1288,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 7,
},
{
    x: 1839,
    y: 1265,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 5,
},
{
    x: 1926,
    y: 1150,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 8,
},
{
    x: 1964,
    y: 1319,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 1,
},
{
    x: 1923,
    y: 1435,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 4,
},
{
    x: 1760,
    y: 1563,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 6,
},
{
    x: 1910,
    y: 1548,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 8,
},
{
    x: 1927,
    y: 1724,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 5,
},
{
    x: 2055,
    y: 1592,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 4,
},
{
    x: 2105,
    y: 1318,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 6,
},
{
    x: 2078,
    y: 1210,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 4,
},
{
    x: 2248,
    y: 1406,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 4,
},
{
    x: 2204,
    y: 1575,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 7,
},
{
    x: 2333,
    y: 1621,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 5,
},
{
    x: 2244,
    y: 1760,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 9,
},
{
    x: 2308,
    y: 1220,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 6,
},
{
    x: 2405,
    y: 1312,
    name: "",
    owner: "Hollynuts", sector: "Hollynuts",
    size: 6,
},
{
    x: 2150,
    y: 846,
    name: "Жилиюль",
    owner: "Hollynuts", sector: "Violet",
    size: 2,
},
{
    x: 2172,
    y: 1033,
    name: "Ригир",
    owner: "Hollynuts", sector: "Violet",
    size: 1,
},
{
    x: 2319,
    y: 795,
    name: "Южени",
    owner: "Hollynuts", sector: "Violet",
    size: 2,
},
{
    x: 2407,
    y: 953,
    name: "Мерктар",
    owner: "Hollynuts", sector: "Violet",
    size: 6,
},
{
    x: 2305,
    y: 1063,
    name: "Кримминис",
    owner: "Hollynuts", sector: "Violet",
    size: 2,
},
{
    x: 1301,
    y: 667,
    name: "Антарес",
    size: 5,
},
{
    x: 1277,
    y: 829,
    name: "Ондерон",
    size: 13,
},
{
    x: 1328,
    y: 759,
    name: "Обан",
    isDestroyed: true,
    size: 20,
},
{
    x: 2409,
    y: 422,
    name: "Скарит",
    size: 7,
},
{
    x: 2252,
    y: 168,
    name: "Праклеяда",
    size: 6,
},
{
    x: 895,
    y: 1583,
    name: "Велоцитрон",
    size: 9,
},
{
    x: 754,
    y: 1616,
    name: "Аниматрон",
    size: 5,
},
{
    x: 853,
    y: 1727,
    name: "Кессион",
    size: 6,
},
];
